spring.application.name=booking-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/booking
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
